routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Auth::routes(['register' => true]);
Route::middleware('auth')->group(function () {
    Route::name('admin.')->prefix('admin')->group(function () {
        // admin or editor
        Route::middleware('role:admin|editor')->group(function () {
            Route::get('/dashboard', 'admin\DashboardController@index')->name('dashboard.index');

            Route::name('profile.')->prefix('/profile-user')->group(function () {
                Route::get('/', 'admin\ProfileController@index')->name('index');
                Route::get('/edit/{id}', 'admin\ProfileController@edit')->name('edit');
                Route::post('/update{id}', 'admin\ProfileController@update')->name('update');
            });
        });

        //Role: admin
        Route::name('users.')->prefix('/users')->group(function () {
            Route::get('/', 'admin\UserController@index')->name('index')->middleware('can:list-user');
            Route::get('/create', 'admin\UserController@create')->name('create')->middleware('can:add-user');
            Route::post('/store', 'admin\UserController@store')->name('store')->middleware('can:add-user');
            Route::get('/edit/{id}', 'admin\UserController@edit')->name('edit')->middleware('can:edit-user');
            Route::post('/update/{id}', 'admin\UserController@update')->name('update')->middleware('can:edit-user');
            Route::get('/destroy/{id}', 'admin\UserController@destroy')->name('destroy')->middleware('can:delete-user');
        });

        Route::name('roles.')->prefix('/roles')->group(function () {
            Route::get('/', 'admin\RoleController@index')->name('index')->middleware('can:list-role');
            Route::get('/create', 'admin\RoleController@create')->name('create')->middleware('can:add-role');
            Route::post('/store', 'admin\RoleController@store')->name('store')->middleware('can:add-role');
            Route::get('/edit/{id}', 'admin\RoleController@edit')->name('edit')->middleware('can:edit-role');
            Route::post('/update/{id}', 'admin\RoleController@update')->name('update')->middleware('can:edit-role');
            Route::get('/destroy/{id}', 'admin\RoleController@destroy')->name('destroy')->middleware('can:delete-role');
        });

        Route::name('permissions.')->prefix('/permissions')->group(function () {
            Route::get('/', 'admin\PermissionController@index')->name('index')->middleware('can:list-permission');
            Route::post('/store', 'admin\PermissionController@store')->name('store')->middleware('can:add-permission');
            Route::get('/destroy/{id}', 'admin\PermissionController@destroy')->name('destroy')->middleware('can:delete-permission');
        });

        Route::name('chatrooms.')->prefix('/chatrooms')->group(function () {
            Route::get('/', 'admin\ChatroomController@index')->name('index')->middleware('can:list-chatroom');
            Route::get('/create', 'admin\ChatroomController@create')->name('create')->middleware('can:add-chatroom');
            Route::post('/store', 'admin\ChatroomController@store')->name('store')->middleware('can:add-chatroom');
            Route::get('/edit/{id}', 'admin\ChatroomController@edit')->name('edit')->middleware('can:edit-chatroom');
            Route::post('/update/{id}', 'admin\ChatroomController@update')->name('update')->middleware('can:edit-chatroom');
            Route::get('/destroy/{id}', 'admin\ChatroomController@destroy')->name('destroy')->middleware('can:delete-chatroom');
        });
        // Role:editor or admin
        Route::name('authors.')->prefix('/authors')->group(function () {
            Route::get('/', 'admin\AuthorController@index')->name('index')->middleware('can:list-author');
            Route::get('/create', 'admin\AuthorController@create')->name('create')->middleware('can:add-author');
            Route::post('/store', 'admin\AuthorController@store')->name('store')->middleware('can:add-author');
            Route::get('/edit/{id}', 'admin\AuthorController@edit')->name('edit')->middleware('can:edit-author');
            Route::post('/update/{id}', 'admin\AuthorController@update')->name('update')->middleware('can:edit-author');
            Route::get('/destroy/{id}', 'admin\AuthorController@destroy')->name('destroy')->middleware('can:delete-author');
        });

        Route::name('products.')->prefix('/products')->group(function () {
            Route::get('/', 'admin\ProductController@index')->name('index')->middleware('can:list-product');
            Route::get('/create', 'admin\ProductController@create')->name('create')->middleware('can:add-product');
            Route::post('/store', 'admin\ProductController@store')->name('store')->middleware('can:add-product');
            Route::get('/edit/{id}', 'admin\ProductController@edit')->name('edit')->middleware('can:edit-product');
            Route::post('/update/{id}', 'admin\ProductController@update')->name('update')->middleware('can:edit-product');
            Route::get('/show/{id}', 'admin\ProductController@show')->name('show')->middleware('can:show-product');
            Route::get('/destroy/{id}', 'admin\ProductController@destroy')->name('destroy')->middleware('can:delete-product');
        });

        Route::name('owners.')->prefix('/owners')->group(function () {
            Route::get('/', 'admin\OwnerController@index')->name('index')->middleware('can:list-owner');
            Route::get('/create', 'admin\OwnerController@create')->name('create')->middleware('can:add-owner');
            Route::post('/store', 'admin\OwnerController@store')->name('store')->middleware('can:add-owner');
            Route::get('/edit/{id}', 'admin\OwnerController@edit')->name('edit')->middleware('can:edit-owner');
            Route::post('/update/{id}', 'admin\OwnerController@update')->name('update')->middleware('can:edit-owner');
            Route::get('/destroy/{id}', 'admin\OwnerController@destroy')->name('destroy')->middleware('can:delete-owner');
        });

        Route::name('posts.')->prefix('/posts')->group(function () {
            Route::get('/', 'admin\PostController@index')->name('index')->middleware('can:list-post');
            Route::get('/create', 'admin\PostController@create')->name('create')->middleware('can:add-post');
            Route::post('/store', 'admin\PostController@store')->name('store')->middleware('can:add-post');
            Route::get('/edit/{id}', 'admin\PostController@edit')->name('edit')->middleware('can:edit-post');
            Route::post('/update/{id}', 'admin\PostController@update')->name('update')->middleware('can:edit-post');
            Route::get('/show/{id}', 'admin\PostController@show')->name('show')->middleware('can:show-post');
            Route::get('/destroy/{id}', 'admin\PostController@destroy')->name('destroy')->middleware('can:delete-post');
        });

        Route::name('faqs.')->prefix('/faqs')->group(function () {
            Route::get('/', 'admin\FaqController@index')->name('index')->middleware('can:list-faq');
            Route::get('/create', 'admin\FaqController@create')->name('create')->middleware('can:add-faq');
            Route::post('/store', 'admin\FaqController@store')->name('store')->middleware('can:add-faq');
            Route::get('/edit/{id}', 'admin\FaqController@edit')->name('edit')->middleware('can:edit-faq');
            Route::post('/update/{id}', 'admin\FaqController@update')->name('update')->middleware('can:edit-faq');
            Route::get('/destroy/{id}', 'admin\FaqController@destroy')->name('destroy')->middleware('can:delete-faq');
        });

        Route::name('tags.')->prefix('/tags')->group(function () {
            Route::get('/', 'admin\TagController@index')->name('index')->middleware('can:list-tag');
            Route::get('/create', 'admin\TagController@create')->name('create')->middleware('can:add-tag');
            Route::post('/store', 'admin\TagController@store')->name('store')->middleware('can:add-tag');
            Route::get('/edit/{id}', 'admin\TagController@edit')->name('edit')->middleware('can:edit-tag');
            Route::post('/update/{id}', 'admin\TagController@update')->name('update')->middleware('can:edit-tag');
            Route::get('/destroy/{id}', 'admin\TagController@destroy')->name('destroy')->middleware('can:delete-tag');
        });

        Route::name('categories.')->prefix('/categories')->group(function () {
            Route::get('/', 'admin\CategoryController@index')->name('index')->middleware('can:list-category');
            Route::get('/get-type', 'admin\CategoryController@getType')->name('getType')->middleware('can:list-category');
            Route::get('/create', 'admin\CategoryController@create')->name('create')->middleware('can:add-category');
            Route::post('/store', 'admin\CategoryController@store')->name('store')->middleware('can:add-category');
            Route::get('/edit/{id}', 'admin\CategoryController@edit')->name('edit')->middleware('can:edit-category');
            Route::post('/update/{id}', 'admin\CategoryController@update')->name('update')->middleware('can:edit-category');
            Route::get('/destroy/{id}', 'admin\CategoryController@destroy')->name('destroy')->middleware('can:delete-category');
        });

        Route::name('documentLaws.')->prefix('/documentLaws')->group(function () {
            Route::get('/', 'admin\DocumentLawController@index')->name('index')->middleware('can:list-documentLaw');
            Route::get('/create', 'admin\DocumentLawController@create')->name('create')->middleware('can:add-documentLaw');
            Route::post('/store', 'admin\DocumentLawController@store')->name('store')->middleware('can:add-documentLaw');
            Route::get('/edit/{id}', 'admin\DocumentLawController@edit')->name('edit')->middleware('can:edit-documentLaw');

app/Http/Controllers/admin/ProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Services\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;


class ProfileController extends Controller
{
    private $userService;

    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }

    public function index()
    {
        try {
            $userId = Auth::user()->id;
            $profile = $this->userService->getById($userId);
            return view('admin.profile.index', compact('profile'));
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', config('consts.message.error.common'));
        }

    }

    public function edit($id)
    {
        try {
            if ($id == Auth::user()->id) {
                $profile = $this->userService->getById($id);
                $profileImg = $profile->image;
                return view('admin.profile.edit', compact('profile', 'profileImg'));
            } else {
                abort(403);
            }
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', config('consts.message.error.common'));
        }

    }

    public function update(Request $request, $id)
    {
        try {
            if ($id == Auth::user()->id) {
                $this->userService->update($request, $id);
                return Redirect(route('admin.profile.index'))->with('success', config('consts.message.success.update')
            );
            } else {
                abort(403);
            }
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', config('consts.message.error.common'));
        }

    }
}

app/Http/Controllers/home/CommentController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use App\Http\Requests\Home\Comment\CommentRequest;
use App\Services\CommentService;
use Illuminate\Support\Facades\Auth;
use App\Services\NotificationService;

class CommentController extends Controller
{
    private $commentService;
    private $notificationService;

    public function __construct(CommentService $commentService, NotificationService $notificationService)
    {
        $this->commentService = $commentService;
        $this->notificationService = $notificationService;
    }

    public function store(CommentRequest $request)
    {
        $comment = $this->commentService->create($request);
        $userPost = $comment->post->user;

        if ($comment->user_id != $userPost->id) {
            $this->notificationService->notiComment($comment, $userPost);
        }
        $others['GetPostByUser'] = route('posts.getPostByUser', ['id' => $comment->user_id]);
        $others['destroyComment'] =  route('comments.destroy', ['id' => $comment->id]);
        $others['updateComment'] =  route('comments.update', ['id' => $comment->id]);
        $others['userImage'] =  asset('image/profile') . '/' . $comment->user->image;
        $others['time'] =  $comment->created_at->diffForHumans();
        $others['_token'] =  csrf_token();

        return response()->json(['comment' => $comment, 'others' => $others]);
    }

    public function update(CommentRequest $request, $id)
    {
        $comment = $this->commentService->update($request, $id);
        return response()->json([
            'message' => config('consts.message.success.update'), 'comment' => $comment
        ]);
    }

    public function toogleStatus($id)
    {
        try {
            $this->commentService->toogleStatus($id);
            return Redirect()->back()->with(
                'success',
                config('consts.message.success.update')
            );
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', config('consts.message.error.common'));
        }
    }

    public function destroy($id)
    {
        $comment = $this->commentService->getById($id);
        if (Auth::user()->id == $comment->user->id || Auth::user()->id == $comment->post->user_id) {
            $commentDeleted = $this->commentService->delete($id);
            if ($commentDeleted) {
                return response()->json(['message' => config('consts.message.success.delete'), 'comment' => $comment]);
            }
        } else {
            abort(403);
        }
    }
}

app/Http/Controllers/home/DocumentLawController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use App\Models\DocumentLaw;
use App\Services\DocumentLawService;
use Illuminate\Http\Request;

use function view;

class DocumentLawController extends Controller
{
    private $documentLawService;

    public function __construct(DocumentLawService $documentLawService)
    {
        $this->documentLawService = $documentLawService;
    }

    public function index(Request $request)
    {
        try {
            $query = DocumentLaw::query();
            $query->getByType(config('consts.documentLaw.type.other.value'));
            if ($request->keyword) {
                $query->search($request->keyword);
            }
            $documentLaws = $query->latest()->paginate(10);
            return view('home.documentLaws.other', compact('documentLaws'));
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', config('consts.message.error.getData'));
        }
    }

    public function getPersonDocument(Request $request)
    {
        try {
            $query = DocumentLaw::query();
            $query->getByType(config('consts.documentLaw.type.person.value'));
            if ($request->keyword) {
                $query->search($request->keyword);
            }
            $documentLaws = $query->latest()->paginate(10);
            return view('home.documentLaws.person', compact('documentLaws'));
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', config('consts.message.error.getData'));
        }
    }

    public function show($id)
    {
        try {
            $documentLaw = $this->documentLawService->getById($id);
            return view('home.documentLaws.show', compact('documentLaw'));
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', config('consts.message.error.common'));
        }
    }
}

app/Http/Controllers/home/FaqController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Faq;
use App\Services\FaqService;
use Illuminate\Http\Request;

use function view;

class FaqController extends Controller
{
    private $faqService;

    public function __construct(FaqService $faqService)
    {
        $this->faqService = $faqService;
    }

    public function index(Request $request)
    {
        try {
            $faqs = Faq::where('category_id', 'null')->latest()->get();
            $categories = Category::where('type', config('consts.category.type.faq.value'))->where('parent_id', 0)->get();
            if ($request->keyword) {
                $searchResults = $this->faqService->search($request);
                return view('home.faq.search-results', compact('searchResults'));
            }
            return view('home.faq.index', compact('faqs', 'categories'));
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', config('consts.message.error.getData'));
        }
    }


    public function getByCategory($id)
    {
        try {
            $category = Category::find($id);
            $faqs = Faq::hasCategoryOrParentCategory($id)->paginate(10);
            return view('home.faq.list', compact('faqs', 'category'));
        } catch (\Throwable $th) {
            return redirect()->back()->with('error', config('consts.message.error.getData'));
        }
    }
}

resources/views/home/profile/edit.blade.php
@extends('layouts.one-column')
@section('title', 'Thông tin tài khoản')
@section('css')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="{{ asset('AdminLTE/plugins/select2/css/select2.min.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="{{ asset('admin/profile/index.css') }}">
    <link rel="stylesheet" href="{{ asset('css/avatar.css') }}">
    <link rel="stylesheet" href="{{ asset('home/post/style.css') }}">
    <style>
        .my-3 {
            margin: 6px 0;
        }

        .border-right {
            border-right: 1px solid #b2c2d2;
        }

        .profile-content {
            margin-top: 50px;
        }
    </style>
@endsection
@section('content')
    <div class="content">
        <div class="container-fluid">
            <form action="{{ route('profile.update', ['id' => $profile->id]) }}" method="POST"
                enctype="multipart/form-data">
                @csrf
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-center" style="font-size: xx-large">Thông tin tài khoản</h4>
                </div>
                <div class="row profile-content">
                    <div class="col-md-6 border-right">
                        <div class="p-3">
                            <div class="">
                                <div class="row my-3">
                                    <div class="col-md-12">
                                        <label class="labels label-required">Họ tên:</label>
                                        <input type="text" value="{{ $profile->name }}" name="name"
                                            class="form-control">
                                        @error('name')
                                            <span class="mt-1 text-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="row my-3">
                                    <div class="col-md-12">
                                        <label class="labels label-required">Giới tính:</label>
                                        <select name="gender" class="form-control" id="gender">
                                            <option value=""></option>
                                            @foreach (config('consts.user.gender') as $gender)
                                                <option
                                                    {{ old('gender') == $gender['value'] || $profile->gender == $gender['value'] ? 'selected' : '' }}
                                                    value="{{ $gender['value'] }}">{{ $gender['name'] }}</option>
                                            @endforeach
                                            @error('gender')
                                                <span class="mt-1 text-danger">{{ $message }}</span>
                                            @enderror
                                        </select>
                                    </div>
                                </div>
                                <div class="row my-3">
                                    <div class="col-md-12">
                                        <label class="labels">Ngày sinh:</label>
                                        <input type="datetime-local" placeholder="yyyy-mm-dd" value="{{ $profile->dob }}"
                                            name="dob" class="form-control" style="background-color: #fff">
                                        @error('dob')
                                            <span class="mt-1 text-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="row my-3">
                                    <div class="col-md-12">
                                        <label class="labels label-required">Email:</label>
                                        <input type="text" value="{{ $profile->email }}" name="email"
                                            class="form-control">
                                        @error('email')
                                            <span class="mt-1 text-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="row my-3">
                                    <div class="col-md-12">
                                        <label class="labels label-required">Điện thoại:</label>
                                        <input type="text" value="{{ $profile->phone }}" name="phone"
                                            class="form-control">
                                        @error('phone')
                                            <span class="mt-1 text-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="row my-3">
                                    <div class="col-md-12">
                                        <label class="labels">Password</label>
                                        <input id="password" data-toggle="password" type="password" name="password"
                                            class="form-control">
                                        @error('password')
                                            <span class="mt-1 text-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 ml-3">
                        <div class="mt-3" style="margin-top: 40px">
                            <div class="d-flex flex-column align-items-center text-center">
                                <div class="avatar-header">
                                    <div class="avatar-wrapper" title="Ảnh đại diện">
                                        <img class="profile-pic avata-img mt-5"
                                            src="
                                            @if ($profile->image) {{ asset('image/profile/' . $profile->image) }} @endif " />
                                        <div class="upload-button">
                                            <i class="fa fa-camera camera-icon" aria-hidden="true"></i>
                                        </div>
                                        <input class="file-upload" name="image" type="file" accept="image/*" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        @role('counselor')
                            <div class="row">
                                <div class="col-md-12">
                                    <label class="labels">Chuyên mục:</label>
                                    <select name="category_id[]" class="form-control select2_init" multiple>
                                        <option></option>
                                        @foreach ($categories as $category)
                                            <option {{ $profile->categories->contains($category->id) ? 'selected' : '' }}
                                                value="{{ $category->id }}">{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        @endrole
                    </div>
                </div>
                <div class="row" style="margin-top: 20px">
                    <div class="text-center">
                        <a href="{{ route('profile.edit', ['id' => $profile->id]) }}">
                            <button class="btn btn-primary profile-button " type="submit">Cập nhật</button>
                        </a>
                    </div>
                </div>
            </form>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
@endsection
@section('js')
    <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>
    <script src="{{ asset('AdminLTE/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('js/avatar.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        $('.select2_init').select2()
        flatpickr("input[type=datetime-local]", {});
    </script>
@endsection

resources/views/home/profile/index.blade.php
@extends('layouts.one-column')
@section('title', 'Thông tin tài khoản')
@section('css')
    <link rel="stylesheet" href="{{ asset('admin/profile/index.css') }}">
    <style>
        .my-3 {
            margin: 6px 0;
        }

        .btn-edit {
            margin-top: 32px;
        }

        .labels {
            font-size: x-large;
            font-weight: 400;
        }

        .image-border {
            border-left: 1px solid #b2c2d2;
        }

        .profile-content {
            margin-top: 50px;
        }

        .avata-img {
            border: 1px solid #060a52;
        }
    </style>
@endsection
@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="d-flex justify-content-between align-items-center mb-3">
                <h4 class="text-center" style="font-size: xx-large">Thông tin tài khoản</h4>
            </div>
            <div class="row profile-content">
                <div class="col-md-6 border-right">
                    <div class="p-3">
                        <div class="">
                            <div class="row my-3">
                                <div class="col-md-12">
                                    <label class="labels">Họ tên: {{ $profile->name }}</label>
                                </div>
                            </div>
                            <div class="row my-3">
                                <div class="col-md-12">
                                    <label class="labels">Giới tính:
                                        @foreach (config('consts.user.gender') as $gender)
                                            @if ($gender['value'] == $profile->gender)
                                                {{ $gender['name'] }}
                                            @endif
                                        @endforeach
                                    </label>
                                </div>
                            </div>
                            <div class="row my-3">
                                <div class="col-md-12">
                                    <label class="labels">Ngày sinh: {{ $profile->dob }}</label>
                                </div>
                            </div>
                            <div class="row my-3">
                                <div class="col-md-12">
                                    <label class="labels">Email: {{ $profile->email }}</label>
                                </div>
                            </div>
                            <div class="row my-3">
                                <div class="col-md-12">
                                    <label class="labels">Điện thoại: {{ $profile->phone }}</label>
                                </div>
                            </div>
                            @role('counselor')
                                <div class="row my-3">
                                    <div class="col-md-12">
                                        <ul id="category" class="tag" style="margin-top: 0 !important">
                                            <label class="labels">Chuyên mục:</label>
                                            @foreach ($profile->categories as $category)
                                                <li class="li-category-tag">
                                                    <a class="m-3"
                                                        href="{{ route('posts.getPostByCategory', ['id' => $category->id]) }}">{{ $category->name ?? 'Chưa rõ' }}</a>
                                                </li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>
                            @endrole
                        </div>
                    </div>
                </div>
                <div class="col-md-6 ml-3 image-border">
                    <div class="mt-3">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img class="avata-img mt-5" src="{{ asset("image/profile/$profile->image") }}">
                            <h4 style="margin-top: 24px !important">Ảnh đại diện</h4>
                            {{-- <span> </span> --}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row btn-edit">
                <div class="text-center">
                    <a href="{{ route('profile.edit', ['id' => $profile->id]) }}">
                        <button class="btn btn-info">Chỉnh sửa</button>
                    </a>
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
@endsection